'use strict';

const OBIMP_BEX_MAX_DATA_LEN = 0x00020000;
exports.OBIMP_BEX_MAX_DATA_LEN = OBIMP_BEX_MAX_DATA_LEN;

const OBIMP_BEX_COM = 0x0001;     // Common.
const OBIMP_BEX_CL = 0x0002;      // Contact list.
const OBIMP_BEX_PRES = 0x0003;    // Presence
const OBIMP_BEX_IM = 0x0004;      // Instant messaging
const OBIMP_BEX_UD = 0x0005;      // Users directory
const OBIMP_BEX_UA = 0x0006;      // User avatars
const OBIMP_BEX_FT = 0x0007;      // File transfer
const OBIMP_BEX_TP = 0x0008;      // Transports
const OBIMP_BEX_WADM = 0xF001;    // Admin Command

exports.OBIMP_BEX_COM = OBIMP_BEX_COM;
exports.OBIMP_BEX_CL = OBIMP_BEX_CL;
exports.OBIMP_BEX_PRES = OBIMP_BEX_PRES;
exports.OBIMP_BEX_IM = OBIMP_BEX_IM;
exports.OBIMP_BEX_UD = OBIMP_BEX_UD;
exports.OBIMP_BEX_UA = OBIMP_BEX_UA;
exports.OBIMP_BEX_FT = OBIMP_BEX_FT;
exports.OBIMP_BEX_TP = OBIMP_BEX_TP;
exports.OBIMP_BEX_WADM = OBIMP_BEX_WADM;


// Common BEX
const OBIMP_BEX_COM_CLI_HELLO = 0x0001;
const OBIMP_BEX_COM_SRV_HELLO = 0x0002;
const OBIMP_BEX_COM_CLI_LOGIN = 0x0003;
const OBIMP_BEX_COM_SRV_LOGIN_REPLY = 0x0004;
const OBIMP_BEX_COM_SRV_BYE = 0x0005;
const OBIMP_BEX_COM_CLI_SRV_KEEPALIVE_PING = 0x0006;
const OBIMP_BEX_COM_CLI_SRV_KEEPALIVE_PONG = 0x0007;
const OBIMP_BEX_COM_CLI_REGISTER = 0x0008;
const OBIMP_BEX_COM_SRV_REGISTER_REPLY = 0x0009;

exports.OBIMP_BEX_COM_CLI_HELLO = OBIMP_BEX_COM_CLI_HELLO;
exports.OBIMP_BEX_COM_SRV_HELLO = OBIMP_BEX_COM_SRV_HELLO;
exports.OBIMP_BEX_COM_CLI_LOGIN = OBIMP_BEX_COM_CLI_LOGIN;
exports.OBIMP_BEX_COM_SRV_LOGIN_REPLY = OBIMP_BEX_COM_SRV_LOGIN_REPLY;
exports.OBIMP_BEX_COM_SRV_BYE = OBIMP_BEX_COM_SRV_BYE;
exports.OBIMP_BEX_COM_CLI_SRV_KEEPALIVE_PING = OBIMP_BEX_COM_CLI_SRV_KEEPALIVE_PING;
exports.OBIMP_BEX_COM_CLI_SRV_KEEPALIVE_PONG = OBIMP_BEX_COM_CLI_SRV_KEEPALIVE_PONG;
exports.OBIMP_BEX_COM_CLI_REGISTER = OBIMP_BEX_COM_CLI_REGISTER;
exports.OBIMP_BEX_COM_SRV_REGISTER_REPLY = OBIMP_BEX_COM_SRV_REGISTER_REPLY;


// Hello error codes:
const HELLO_ERROR_ACCOUNT_INVALID = 0x0001;
const HELLO_ERROR_SERVICE_TEMP_UNAVAILABLE = 0x0002;
const HELLO_ERROR_ACCOUNT_BANNED = 0x0003;
const HELLO_ERROR_WRONG_COOKIE = 0x0004;
const HELLO_ERROR_TOO_MANY_CLIENTS = 0x0005;
const HELLO_ERROR_INVALID_LOGIN = 0x0006;

exports.HELLO_ERROR_ACCOUNT_INVALID = HELLO_ERROR_ACCOUNT_INVALID;
exports.HELLO_ERROR_SERVICE_TEMP_UNAVAILABLE = HELLO_ERROR_SERVICE_TEMP_UNAVAILABLE;
exports.HELLO_ERROR_ACCOUNT_BANNED = HELLO_ERROR_ACCOUNT_BANNED;
exports.HELLO_ERROR_WRONG_COOKIE = HELLO_ERROR_WRONG_COOKIE;
exports.HELLO_ERROR_TOO_MANY_CLIENTS = HELLO_ERROR_TOO_MANY_CLIENTS;
exports.HELLO_ERROR_INVALID_LOGIN = HELLO_ERROR_INVALID_LOGIN;

//Login error codes:
const LOGIN_ERROR_ACCOUNT_INVALID = 0x0001;
const LOGIN_ERROR_SERVICE_TEMP_UNAVAILABLE = 0x0002;
const LOGIN_ERROR_ACCOUNT_BANNED = 0x0003;
const LOGIN_ERROR_WRONG_PASSWORD = 0x0004;
const LOGIN_ERROR_INVALID_LOGIN = 0x0005;
exports.LOGIN_ERROR_ACCOUNT_INVALID = LOGIN_ERROR_ACCOUNT_INVALID;
exports.LOGIN_ERROR_SERVICE_TEMP_UNAVAILABLE = LOGIN_ERROR_SERVICE_TEMP_UNAVAILABLE;
exports.LOGIN_ERROR_ACCOUNT_BANNED = LOGIN_ERROR_ACCOUNT_BANNED;
exports.LOGIN_ERROR_WRONG_PASSWORD = LOGIN_ERROR_WRONG_PASSWORD;
exports.LOGIN_ERROR_INVALID_LOGIN = LOGIN_ERROR_INVALID_LOGIN;

// Contact list BEX
const OBIMP_BEX_CL_CLI_PARAMS = 0x0001;
const OBIMP_BEX_CL_SRV_PARAMS_REPLY = 0x0002;
const OBIMP_BEX_CL_CLI_REQUEST = 0x0003;
const OBIMP_BEX_CL_SRV_REPLY = 0x0004;
const OBIMP_BEX_CL_CLI_VERIFY = 0x0005;
const OBIMP_BEX_CL_SRV_VERIFY_REPLY = 0x0006;
const OBIMP_BEX_CL_CLI_ADD_ITEM = 0x0007;
const OBIMP_BEX_CL_SRV_ADD_ITEM_REPLY = 0x0008;
const OBIMP_BEX_CL_CLI_DEL_ITEM = 0x0009;
const OBIMP_BEX_CL_SRV_DEL_ITEM_REPLY = 0x000a;
const OBIMP_BEX_CL_CLI_UPD_ITEM = 0x000b;
const OBIMP_BEX_CL_SRV_UPD_ITEM_REPLY = 0x000c;
const OBIMP_BEX_CL_CLI_SRV_AUTH_REQUEST = 0x000d;
const OBIMP_BEX_CL_CLI_SRV_AUTH_REPLY = 0x000e;
const OBIMP_BEX_CL_CLI_SRV_AUTH_REVOKE = 0x000f;
const OBIMP_BEX_CL_CLI_REQ_OFFAUTH = 0x0010;
const OBIMP_BEX_CL_SRV_DONE_OFFAUTH = 0x0011;
const OBIMP_BEX_CL_CLI_DEL_OFFAUTH = 0x0012;
const OBIMP_BEX_CL_SRV_ITEM_OPER = 0x0013;
const OBIMP_BEX_CL_SRV_BEGIN_UPDATE = 0x0014;
const OBIMP_BEX_CL_SRV_END_UPDATE = 0x0015;
exports.OBIMP_BEX_CL_CLI_PARAMS = OBIMP_BEX_CL_CLI_PARAMS;
exports.OBIMP_BEX_CL_SRV_PARAMS_REPLY = OBIMP_BEX_CL_SRV_PARAMS_REPLY;
exports.OBIMP_BEX_CL_CLI_REQUEST = OBIMP_BEX_CL_CLI_REQUEST;
exports.OBIMP_BEX_CL_SRV_REPLY = OBIMP_BEX_CL_SRV_REPLY;
exports.OBIMP_BEX_CL_CLI_VERIFY = OBIMP_BEX_CL_CLI_VERIFY;
exports.OBIMP_BEX_CL_SRV_VERIFY_REPLY = OBIMP_BEX_CL_SRV_VERIFY_REPLY;
exports.OBIMP_BEX_CL_CLI_ADD_ITEM = OBIMP_BEX_CL_CLI_ADD_ITEM;
exports.OBIMP_BEX_CL_SRV_ADD_ITEM_REPLY = OBIMP_BEX_CL_SRV_ADD_ITEM_REPLY;
exports.OBIMP_BEX_CL_CLI_DEL_ITEM = OBIMP_BEX_CL_CLI_DEL_ITEM;
exports.OBIMP_BEX_CL_SRV_DEL_ITEM_REPLY = OBIMP_BEX_CL_SRV_DEL_ITEM_REPLY;
exports.OBIMP_BEX_CL_CLI_UPD_ITEM = OBIMP_BEX_CL_CLI_UPD_ITEM;
exports.OBIMP_BEX_CL_SRV_UPD_ITEM_REPLY = OBIMP_BEX_CL_SRV_UPD_ITEM_REPLY;
exports.OBIMP_BEX_CL_CLI_SRV_AUTH_REQUEST = OBIMP_BEX_CL_CLI_SRV_AUTH_REQUEST;
exports.OBIMP_BEX_CL_CLI_SRV_AUTH_REPLY = OBIMP_BEX_CL_CLI_SRV_AUTH_REPLY;
exports.OBIMP_BEX_CL_CLI_SRV_AUTH_REVOKE = OBIMP_BEX_CL_CLI_SRV_AUTH_REVOKE;
exports.OBIMP_BEX_CL_CLI_REQ_OFFAUTH = OBIMP_BEX_CL_CLI_REQ_OFFAUTH;
exports.OBIMP_BEX_CL_SRV_DONE_OFFAUTH = OBIMP_BEX_CL_SRV_DONE_OFFAUTH;
exports.OBIMP_BEX_CL_CLI_DEL_OFFAUTH = OBIMP_BEX_CL_CLI_DEL_OFFAUTH;
exports.OBIMP_BEX_CL_SRV_ITEM_OPER = OBIMP_BEX_CL_SRV_ITEM_OPER;
exports.OBIMP_BEX_CL_SRV_BEGIN_UPDATE = OBIMP_BEX_CL_SRV_BEGIN_UPDATE;
exports.OBIMP_BEX_CL_SRV_END_UPDATE = OBIMP_BEX_CL_SRV_END_UPDATE;


// Contact list item types:
const CL_ITEM_TYPE_GROUP = 0x0001;
const CL_ITEM_TYPE_CONTACT = 0x0002;
const CL_ITEM_TYPE_TRANSPORT = 0x0003;
const CL_ITEM_TYPE_NOTE = 0x0004;
exports.CL_ITEM_TYPE_GROUP = CL_ITEM_TYPE_GROUP;
exports.CL_ITEM_TYPE_CONTACT = CL_ITEM_TYPE_CONTACT;
exports.CL_ITEM_TYPE_TRANSPORT = CL_ITEM_TYPE_TRANSPORT;
exports.CL_ITEM_TYPE_NOTE = CL_ITEM_TYPE_NOTE;
// Contact privacy types:
const CL_PRIV_TYPE_NONE = 0x00;
const CL_PRIV_TYPE_VISIBLE_LIST = 0x01;
const CL_PRIV_TYPE_INVISIBLE_LIST = 0x02;
const CL_PRIV_TYPE_IGNORE_LIST = 0x03;
const CL_PRIV_TYPE_IGNORE_NOT_IN_LIST = 0x04;
exports.CL_PRIV_TYPE_NONE = CL_PRIV_TYPE_NONE;
exports.CL_PRIV_TYPE_VISIBLE_LIST = CL_PRIV_TYPE_VISIBLE_LIST;
exports.CL_PRIV_TYPE_INVISIBLE_LIST = CL_PRIV_TYPE_INVISIBLE_LIST;
exports.CL_PRIV_TYPE_IGNORE_LIST = CL_PRIV_TYPE_IGNORE_LIST;
exports.CL_PRIV_TYPE_IGNORE_NOT_IN_LIST = CL_PRIV_TYPE_IGNORE_NOT_IN_LIST;

// Notes types:
const CL_NOTE_TYPE_TEXT = 0x00;
const CL_NOTE_TYPE_COMMAND = 0x01;
const CL_NOTE_TYPE_LINK = 0x02;
const CL_NOTE_TYPE_EMAIL = 0x03;
const CL_NOTE_TYPE_PHONE = 0x04;
exports.CL_NOTE_TYPE_TEXT = CL_NOTE_TYPE_TEXT;
exports.CL_NOTE_TYPE_COMMAND = CL_NOTE_TYPE_COMMAND;
exports.CL_NOTE_TYPE_LINK = CL_NOTE_TYPE_LINK;
exports.CL_NOTE_TYPE_EMAIL = CL_NOTE_TYPE_EMAIL;
exports.CL_NOTE_TYPE_PHONE = CL_NOTE_TYPE_PHONE;

// Adding result codes:
const ADD_RES_SUCCESS = 0x0000;
const ADD_RES_ERROR_WRONG_ITEM_TYPE = 0x0001;
const ADD_RES_ERROR_WRONG_PARENT_GROUP = 0x0002;
const ADD_RES_ERROR_NAME_LEN_LIMIT = 0x0003;
const ADD_RES_ERROR_WRONG_NAME = 0x0004;
const ADD_RES_ERROR_ITEM_ALREADY_EXISTS = 0x0005;
const ADD_RES_ERROR_ITEM_LIMIT_REACHED = 0x0006;
const ADD_RES_ERROR_BAD_REQUEST = 0x0007;
const ADD_RES_ERROR_BAD_ITEM_STLD = 0x0008;
const ADD_RES_ERROR_NOT_ALLOWED = 0x0009;
exports.ADD_RES_SUCCESS = ADD_RES_SUCCESS;
exports.ADD_RES_ERROR_WRONG_ITEM_TYPE = ADD_RES_ERROR_WRONG_ITEM_TYPE;
exports.ADD_RES_ERROR_WRONG_PARENT_GROUP = ADD_RES_ERROR_WRONG_PARENT_GROUP;
exports.ADD_RES_ERROR_NAME_LEN_LIMIT = ADD_RES_ERROR_NAME_LEN_LIMIT;
exports.ADD_RES_ERROR_WRONG_NAME = ADD_RES_ERROR_WRONG_NAME;
exports.ADD_RES_ERROR_ITEM_ALREADY_EXISTS = ADD_RES_ERROR_ITEM_ALREADY_EXISTS;
exports.ADD_RES_ERROR_ITEM_LIMIT_REACHED = ADD_RES_ERROR_ITEM_LIMIT_REACHED;
exports.ADD_RES_ERROR_BAD_REQUEST = ADD_RES_ERROR_BAD_REQUEST;
exports.ADD_RES_ERROR_BAD_ITEM_STLD = ADD_RES_ERROR_BAD_ITEM_STLD;
exports.ADD_RES_ERROR_NOT_ALLOWED = ADD_RES_ERROR_NOT_ALLOWED;

// Deletion result codes:
const DEL_RES_SUCCESS = 0x0000;
const DEL_RES_ERROR_NOT_FOUND = 0x0001;
const DEL_RES_ERROR_NOT_ALLOWED = 0x0002;
const DEL_RES_ERROR_GROUP_NOT_EMPTY = 0x0003;
exports.DEL_RES_SUCCESS = DEL_RES_SUCCESS;
exports.DEL_RES_ERROR_NOT_FOUND = DEL_RES_ERROR_NOT_FOUND;
exports.DEL_RES_ERROR_NOT_ALLOWED = DEL_RES_ERROR_NOT_ALLOWED;
exports.DEL_RES_ERROR_GROUP_NOT_EMPTY = DEL_RES_ERROR_GROUP_NOT_EMPTY;

// Update operation result codes:
const UPD_RES_SUCCESS = 0x0000;
const UPD_RES_ERROR_NOT_FOUND = 0x0001;
const UPD_RES_ERROR_WRONG_PARENT_GROUP = 0x0002;
const UPD_RES_ERROR_NAME_LEN_LIMIT = 0x0003;
const UPD_RES_ERROR_WRONG_NAME = 0x0004;
const UPD_RES_ERROR_ITEM_ALREADY_EXISTS = 0x0005;
const UPD_RES_ERROR_BAD_REQUEST = 0x0006;
const UPD_RES_ERROR_BAD_ITEM_STLD = 0x0007;
const UPD_RES_ERROR_NOT_ALLOWED = 0x0008;
exports.UPD_RES_SUCCESS = UPD_RES_SUCCESS;
exports.UPD_RES_ERROR_NOT_FOUND = UPD_RES_ERROR_NOT_FOUND;
exports.UPD_RES_ERROR_WRONG_PARENT_GROUP = UPD_RES_ERROR_WRONG_PARENT_GROUP;
exports.UPD_RES_ERROR_NAME_LEN_LIMIT = UPD_RES_ERROR_NAME_LEN_LIMIT;
exports.UPD_RES_ERROR_WRONG_NAME = UPD_RES_ERROR_WRONG_NAME;
exports.UPD_RES_ERROR_ITEM_ALREADY_EXISTS = UPD_RES_ERROR_ITEM_ALREADY_EXISTS;
exports.UPD_RES_ERROR_BAD_REQUEST = UPD_RES_ERROR_BAD_REQUEST;
exports.UPD_RES_ERROR_BAD_ITEM_STLD = UPD_RES_ERROR_BAD_ITEM_STLD;
exports.UPD_RES_ERROR_NOT_ALLOWED = UPD_RES_ERROR_NOT_ALLOWED;

// Authorization reply code:
const AUTH_REPLY_GRANTED = 0x0001;
const AUTH_REPLY_DENIED = 0x0002;
exports.AUTH_REPLY_GRANTED = AUTH_REPLY_GRANTED;
exports.AUTH_REPLY_DENIED = AUTH_REPLY_DENIED;

// Server operation codes:
const OPER_ADD_ITEM = 0x0001;
const OPER_DEL_ITEM = 0x0002;
const OPER_UPD_ITEM = 0x0003;
exports.OPER_ADD_ITEM = OPER_ADD_ITEM;
exports.OPER_DEL_ITEM = OPER_DEL_ITEM;
exports.OPER_UPD_ITEM = OPER_UPD_ITEM;

// Presence BEX
const OBIMP_BEX_PRES_CLI_PARAMS = 0x0001;
const OBIMP_BEX_PRES_SRV_PARAMS_REPLY = 0x0002;
const OBIMP_BEX_PRES_CLI_SET_PRES_INFO = 0x0003;
const OBIMP_BEX_PRES_CLI_SET_STATUS = 0x0004;
const OBIMP_BEX_PRES_CLI_ACTIVATE = 0x0005;
const OBIMP_BEX_PRES_SRV_CONTACT_ONLINE = 0x0006;
const OBIMP_BEX_PRES_SRV_CONTACT_OFFLINE = 0x0007;
const OBIMP_BEX_PRES_CLI_REQ_PRES_INFO = 0x0008;
const OBIMP_BEX_PRES_SRV_PRES_INFO = 0x0009;
const OBIMP_BEX_PRES_SRV_MAIL_NOTIF = 0x000A;
const OBIMP_BEX_PRES_CLI_REQ_OWN_MAIL_URL = 0x000B;
const OBIMP_BEX_PRES_SRV_OWN_MAIL_URL = 0x000C;
exports.OBIMP_BEX_PRES_CLI_PARAMS = OBIMP_BEX_PRES_CLI_PARAMS;
exports.OBIMP_BEX_PRES_SRV_PARAMS_REPLY = OBIMP_BEX_PRES_SRV_PARAMS_REPLY;
exports.OBIMP_BEX_PRES_CLI_SET_PRES_INFO = OBIMP_BEX_PRES_CLI_SET_PRES_INFO;
exports.OBIMP_BEX_PRES_CLI_SET_STATUS = OBIMP_BEX_PRES_CLI_SET_STATUS;
exports.OBIMP_BEX_PRES_CLI_ACTIVATE = OBIMP_BEX_PRES_CLI_ACTIVATE;
exports.OBIMP_BEX_PRES_SRV_CONTACT_ONLINE = OBIMP_BEX_PRES_SRV_CONTACT_ONLINE;
exports.OBIMP_BEX_PRES_SRV_CONTACT_OFFLINE = OBIMP_BEX_PRES_SRV_CONTACT_OFFLINE;
exports.OBIMP_BEX_PRES_CLI_REQ_PRES_INFO = OBIMP_BEX_PRES_CLI_REQ_PRES_INFO;
exports.OBIMP_BEX_PRES_SRV_PRES_INFO = OBIMP_BEX_PRES_SRV_PRES_INFO;
exports.OBIMP_BEX_PRES_SRV_MAIL_NOTIF = OBIMP_BEX_PRES_SRV_MAIL_NOTIF;
exports.OBIMP_BEX_PRES_CLI_REQ_OWN_MAIL_URL = OBIMP_BEX_PRES_CLI_REQ_OWN_MAIL_URL;
exports.OBIMP_BEX_PRES_SRV_OWN_MAIL_URL = OBIMP_BEX_PRES_SRV_OWN_MAIL_URL;

// Available client capabilities:
const CAP_MSGS_UTF8 = 0x0001;       // UTF-8 encoding messages support (required for all clients)
const CAP_MSGS_RTF = 0x0002;        // RTF (Rich Text Format) messages support with UTF-8 encoding
const CAP_MSGS_HTML = 0x0003;       // HTML (HyperText Markup Language) messages support with UTF-8 encoding
const CAP_MSGS_ENCRYPT = 0x0004;    // Encryption support
const CAP_NOTIFS_TYPING = 0x0005;   // Typing notifications support
const CAP_AVATARS = 0x0006;         // Avatars support
const CAP_FILE_TRANSFER = 0x0007;   // File transfer support
const CAP_TRANSPORTS = 0x0008;      // Transports support
const CAP_NOTIFS_ALARM = 0x0009;    // Alarm notifications support
const CAP_NOTIFS_MAIL = 0x000A;     // Mail notifications support
exports.CAP_MSGS_UTF8 = CAP_MSGS_UTF8;
exports.CAP_MSGS_RTF = CAP_MSGS_RTF;
exports.CAP_MSGS_HTML = CAP_MSGS_HTML;
exports.CAP_MSGS_ENCRYPT = CAP_MSGS_ENCRYPT;
exports.CAP_NOTIFS_TYPING = CAP_NOTIFS_TYPING;
exports.CAP_AVATARS = CAP_AVATARS;
exports.CAP_FILE_TRANSFER = CAP_FILE_TRANSFER;
exports.CAP_TRANSPORTS = CAP_TRANSPORTS;
exports.CAP_NOTIFS_ALARM = CAP_NOTIFS_ALARM;
exports.CAP_NOTIFS_MAIL = CAP_NOTIFS_MAIL;

// Available client types:
const CLIENT_TYPE_USER = 0x0001;
const CLIENT_TYPE_BOT = 0x0002;
const CLIENT_TYPE_SERVICE = 0x0003;
exports.CLIENT_TYPE_USER = CLIENT_TYPE_USER;
exports.CLIENT_TYPE_BOT = CLIENT_TYPE_BOT;
exports.CLIENT_TYPE_SERVICE = CLIENT_TYPE_SERVICE;

// Available default presence status values:
const PRES_STATUS_ONLINE = 0x0000;
const PRES_STATUS_INVISIBLE = 0x0001;
const PRES_STATUS_INVISIBLE_FOR_ALL = 0x0002;
const PRES_STATUS_FREE_FOR_CHAT = 0x0003;
const PRES_STATUS_AT_HOME = 0x0004;
const PRES_STATUS_AT_WORK = 0x0005;
const PRES_STATUS_LUNCH = 0x0006;
const PRES_STATUS_AWAY = 0x0007;
const PRES_STATUS_NOT_AVAILABLE = 0x0008;
const PRES_STATUS_OCCUPIED = 0x0009;
const PRES_STATUS_DO_NOT_DISTURB = 0x000A;
exports.PRES_STATUS_ONLINE = PRES_STATUS_ONLINE;
exports.PRES_STATUS_INVISIBLE = PRES_STATUS_INVISIBLE;
exports.PRES_STATUS_INVISIBLE_FOR_ALL = PRES_STATUS_INVISIBLE_FOR_ALL;
exports.PRES_STATUS_FREE_FOR_CHAT = PRES_STATUS_FREE_FOR_CHAT;
exports.PRES_STATUS_AT_HOME = PRES_STATUS_AT_HOME;
exports.PRES_STATUS_AT_WORK = PRES_STATUS_AT_WORK;
exports.PRES_STATUS_LUNCH = PRES_STATUS_LUNCH;
exports.PRES_STATUS_AWAY = PRES_STATUS_AWAY;
exports.PRES_STATUS_NOT_AVAILABLE = PRES_STATUS_NOT_AVAILABLE;
exports.PRES_STATUS_OCCUPIED = PRES_STATUS_OCCUPIED;
exports.PRES_STATUS_DO_NOT_DISTURB = PRES_STATUS_DO_NOT_DISTURB;

// BEX 0x0004, Instant messaging (OBIMP_BEX_IM)
const OBIMP_BEX_IM_CLI_PARAMS = 0x0001;
const OBIMP_BEX_IM_SRV_PARAMS_REPLY = 0x0002;
const OBIMP_BEX_IM_CLI_REQ_OFFLINE = 0x0003;
const OBIMP_BEX_IM_SRV_DONE_OFFLINE = 0x0004;
const OBIMP_BEX_IM_CLI_DEL_OFFLINE = 0x0005;
const OBIMP_BEX_IM_CLI_MESSAGE = 0x0006;
const OBIMP_BEX_IM_SRV_MESSAGE = 0x0007;
const OBIMP_BEX_IM_CLI_SRV_MSG_REPORT = 0x0008;
const OBIMP_BEX_IM_CLI_SRV_NOTIFY = 0x0009;
const OBIMP_BEX_IM_CLI_SRV_ENCRYPT_KEY_REQ = 0x000A;
const OBIMP_BEX_IM_CLI_SRV_ENCRYPT_KEY_REPLY = 0x000B;
const OBIMP_BEX_IM_CLI_MULTIPLE_MSG = 0x000C;
exports.OBIMP_BEX_IM_CLI_PARAMS = OBIMP_BEX_IM_CLI_PARAMS;
exports.OBIMP_BEX_IM_SRV_PARAMS_REPLY = OBIMP_BEX_IM_SRV_PARAMS_REPLY;
exports.OBIMP_BEX_IM_CLI_REQ_OFFLINE = OBIMP_BEX_IM_CLI_REQ_OFFLINE;
exports.OBIMP_BEX_IM_SRV_DONE_OFFLINE = OBIMP_BEX_IM_SRV_DONE_OFFLINE;
exports.OBIMP_BEX_IM_CLI_DEL_OFFLINE = OBIMP_BEX_IM_CLI_DEL_OFFLINE;
exports.OBIMP_BEX_IM_CLI_MESSAGE = OBIMP_BEX_IM_CLI_MESSAGE;
exports.OBIMP_BEX_IM_SRV_MESSAGE = OBIMP_BEX_IM_SRV_MESSAGE;
exports.OBIMP_BEX_IM_CLI_SRV_MSG_REPORT = OBIMP_BEX_IM_CLI_SRV_MSG_REPORT;
exports.OBIMP_BEX_IM_CLI_SRV_NOTIFY = OBIMP_BEX_IM_CLI_SRV_NOTIFY;
exports.OBIMP_BEX_IM_CLI_SRV_ENCRYPT_KEY_REQ = OBIMP_BEX_IM_CLI_SRV_ENCRYPT_KEY_REQ;
exports.OBIMP_BEX_IM_CLI_SRV_ENCRYPT_KEY_REPLY = OBIMP_BEX_IM_CLI_SRV_ENCRYPT_KEY_REPLY;
exports.OBIMP_BEX_IM_CLI_MULTIPLE_MSG = OBIMP_BEX_IM_CLI_MULTIPLE_MSG;

// Message types:
const MSG_TYPE_UTF8 = 0x0001;   // UTF-8 encoded message (base type)
const MSG_TYPE_RTF = 0x0002;    // RTF (Rich Text Format) message with UTF-8 encoding
const MSG_TYPE_HTML = 0x0003;   // HTML (HyperText Markup Language) message with UTF-8
exports.MSG_TYPE_UTF8 = MSG_TYPE_UTF8;
exports.MSG_TYPE_RTF = MSG_TYPE_RTF;
exports.MSG_TYPE_HTML = MSG_TYPE_HTML;

// BEX 0x0005, Users directory (OBIMP_BEX_UD)
const OBIMP_BEX_UD_CLI_PARAMS = 0x0001;
const OBIMP_BEX_UD_SRV_PARAMS_REPLY = 0x0002;
const OBIMP_BEX_UD_CLI_DETAILS_REQ = 0x0003;
const OBIMP_BEX_UD_SRV_DETAILS_REQ_REPLY = 0x0004;
const OBIMP_BEX_UD_CLI_DETAILS_UPD = 0x0005;
const OBIMP_BEX_UD_SRV_DETAILS_UPD_REPLY = 0x0006;
const OBIMP_BEX_UD_CLI_SEARCH = 0x0007;
const OBIMP_BEX_UD_SRV_SEARCH_REPLY = 0x0008;
const OBIMP_BEX_UD_CLI_SECURE_UPD = 0x0009;
const OBIMP_BEX_UD_SRV_SECURE_UPD_REPLY = 0x000A;
exports.OBIMP_BEX_UD_CLI_PARAMS = OBIMP_BEX_UD_CLI_PARAMS;
exports.OBIMP_BEX_UD_SRV_PARAMS_REPLY = OBIMP_BEX_UD_SRV_PARAMS_REPLY;
exports.OBIMP_BEX_UD_CLI_DETAILS_REQ = OBIMP_BEX_UD_CLI_DETAILS_REQ;
exports.OBIMP_BEX_UD_SRV_DETAILS_REQ_REPLY = OBIMP_BEX_UD_SRV_DETAILS_REQ_REPLY;
exports.OBIMP_BEX_UD_CLI_DETAILS_UPD = OBIMP_BEX_UD_CLI_DETAILS_UPD;
exports.OBIMP_BEX_UD_SRV_DETAILS_UPD_REPLY = OBIMP_BEX_UD_SRV_DETAILS_UPD_REPLY;
exports.OBIMP_BEX_UD_CLI_SEARCH = OBIMP_BEX_UD_CLI_SEARCH;
exports.OBIMP_BEX_UD_SRV_SEARCH_REPLY = OBIMP_BEX_UD_SRV_SEARCH_REPLY;
exports.OBIMP_BEX_UD_CLI_SECURE_UPD = OBIMP_BEX_UD_CLI_SECURE_UPD;
exports.OBIMP_BEX_UD_SRV_SECURE_UPD_REPLY = OBIMP_BEX_UD_SRV_SECURE_UPD_REPLY;

// User details request result codes:
const DETAILS_RES_SUCCESS = 0x0000;
const DETAILS_RES_NOT_FOUND = 0x0001;
const DETAILS_RES_TOO_MANY_REQUESTS = 0x0002;
const DETAILS_RES_SERVICE_TEMP_UNAVAILABLE = 0x0003;
exports.DETAILS_RES_SUCCESS = DETAILS_RES_SUCCESS;
exports.DETAILS_RES_NOT_FOUND = DETAILS_RES_NOT_FOUND;
exports.DETAILS_RES_TOO_MANY_REQUESTS = DETAILS_RES_TOO_MANY_REQUESTS;
exports.DETAILS_RES_SERVICE_TEMP_UNAVAILABLE = DETAILS_RES_SERVICE_TEMP_UNAVAILABLE;

// Update details result codes:
const UPD_DETAILS_RES_SUCCESS = 0x0000;
const UPD_DETAILS_RES_BAD_REQUEST = 0x0001;
const UPD_DETAILS_RES_SERVICE_TEMP_UNAVAILABLE = 0x0002;
const UPD_DETAILS_RES_NOT_ALLOWED = 0x0003;
exports.UPD_DETAILS_RES_SUCCESS = UPD_DETAILS_RES_SUCCESS;
exports.UPD_DETAILS_RES_BAD_REQUEST = UPD_DETAILS_RES_BAD_REQUEST;
exports.UPD_DETAILS_RES_SERVICE_TEMP_UNAVAILABLE = UPD_DETAILS_RES_SERVICE_TEMP_UNAVAILABLE;
exports.UPD_DETAILS_RES_NOT_ALLOWED = UPD_DETAILS_RES_NOT_ALLOWED;

// Zodiac signs:
const ZODIAC_ARIES = 0x01;
const ZODIAC_TAURUS = 0x02;
const ZODIAC_GEMINI = 0x03;
const ZODIAC_CANCER = 0x04;
const ZODIAC_LEO = 0x05;
const ZODIAC_VIRGO = 0x06;
const ZODIAC_LIBRA = 0x07;
const ZODIAC_SCORPIO = 0x08;
const ZODIAC_SAGITTARIUS = 0x09;
const ZODIAC_CAPRICORN = 0x0A;
const ZODIAC_AQUARIUS = 0x0B;
const ZODIAC_PISCES = 0x0C;
exports.ZODIAC_ARIES = ZODIAC_ARIES;
exports.ZODIAC_TAURUS = ZODIAC_TAURUS;
exports.ZODIAC_GEMINI = ZODIAC_GEMINI;
exports.ZODIAC_CANCER = ZODIAC_CANCER;
exports.ZODIAC_LEO = ZODIAC_LEO;
exports.ZODIAC_VIRGO = ZODIAC_VIRGO;
exports.ZODIAC_LIBRA = ZODIAC_LIBRA;
exports.ZODIAC_SCORPIO = ZODIAC_SCORPIO;
exports.ZODIAC_SAGITTARIUS = ZODIAC_SAGITTARIUS;
exports.ZODIAC_CAPRICORN = ZODIAC_CAPRICORN;
exports.ZODIAC_AQUARIUS = ZODIAC_AQUARIUS;
exports.ZODIAC_PISCES = ZODIAC_PISCES;

// Search result codes:
const SEARCH_RES_SUCCESS = 0x0000;
const SEARCH_RES_NOT_FOUND = 0x0001;
const SEARCH_RES_BAD_REQUEST = 0x0002;
const SEARCH_RES_TOO_MANY_REQUESTS = 0x0003;
const SEARCH_RES_SERVICE_TEMP_UNAVAILABLE = 0x0004;
exports.SEARCH_RES_SUCCESS = SEARCH_RES_SUCCESS;
exports.SEARCH_RES_NOT_FOUND = SEARCH_RES_NOT_FOUND;
exports.SEARCH_RES_BAD_REQUEST = SEARCH_RES_BAD_REQUEST;
exports.SEARCH_RES_TOO_MANY_REQUESTS = SEARCH_RES_TOO_MANY_REQUESTS;
exports.SEARCH_RES_SERVICE_TEMP_UNAVAILABLE = SEARCH_RES_SERVICE_TEMP_UNAVAILABLE;

// Available status picture flags:
const SEARCH_ST_PIC_FLAG_CUSTOM = 0x00010000;
exports.SEARCH_ST_PIC_FLAG_CUSTOM = SEARCH_ST_PIC_FLAG_CUSTOM;

// Update details result codes:
const UPD_SECURE_RES_SUCCESS = 0x0000;
const UPD_SECURE_RES_BAD_REQUEST = 0x0001;
const UPD_SECURE_RES_SERVICE_TEMP_UNAVAILABLE = 0x0002;
const UPD_SECURE_RES_NOT_ALLOWED = 0x0003;

// Update details result codes:alexey-m
exports.UPD_SECURE_RES_SUCCESS = UPD_SECURE_RES_SUCCESS;
exports.UPD_SECURE_RES_BAD_REQUEST = UPD_SECURE_RES_BAD_REQUEST;
exports.UPD_SECURE_RES_SERVICE_TEMP_UNAVAILABLE = UPD_SECURE_RES_SERVICE_TEMP_UNAVAILABLE;
exports.UPD_SECURE_RES_NOT_ALLOWED = UPD_SECURE_RES_NOT_ALLOWED;

// BEX 0x0006, User avatars (OBIMP_BEX_UA)
const OBIMP_BEX_UA_CLI_PARAMS = 0x0001;
const OBIMP_BEX_UA_SRV_PARAMS_REPLY = 0x0002;
const OBIMP_BEX_UA_CLI_AVATAR_REQ = 0x0003;
const OBIMP_BEX_UA_SRV_AVATAR_REPLY = 0x0004;
const OBIMP_BEX_UA_CLI_AVATAR_SET = 0x0005;
const OBIMP_BEX_UA_SRV_AVATAR_SET_REPLY = 0x0006;
exports.OBIMP_BEX_UA_CLI_PARAMS = OBIMP_BEX_UA_CLI_PARAMS;
exports.OBIMP_BEX_UA_SRV_PARAMS_REPLY = OBIMP_BEX_UA_SRV_PARAMS_REPLY;
exports.OBIMP_BEX_UA_CLI_AVATAR_REQ = OBIMP_BEX_UA_CLI_AVATAR_REQ;
exports.OBIMP_BEX_UA_SRV_AVATAR_REPLY = OBIMP_BEX_UA_SRV_AVATAR_REPLY;
exports.OBIMP_BEX_UA_CLI_AVATAR_SET = OBIMP_BEX_UA_CLI_AVATAR_SET;
exports.OBIMP_BEX_UA_SRV_AVATAR_SET_REPLY = OBIMP_BEX_UA_SRV_AVATAR_SET_REPLY;

// Avatar request result:
const AVATAR_REQ_SUCCESS = 0x0000;
const AVATAR_REQ_NOT_FOUND = 0x0001;
const AVATAR_REQ_NOT_ALLOWED = 0x0002;
exports.AVATAR_REQ_SUCCESS = AVATAR_REQ_SUCCESS;
exports.AVATAR_REQ_NOT_FOUND = AVATAR_REQ_NOT_FOUND;
exports.AVATAR_REQ_NOT_ALLOWED = AVATAR_REQ_NOT_ALLOWED;

// Avatar set result:
const AVATAR_SET_SUCCESS = 0x0000;
const AVATAR_SET_BAD_MD5 = 0x0001;
const AVATAR_SET_NOT_ALLOWED = 0x0002;
const AVATAR_SET_TEMP_UNAVAILABLE = 0x0003;
const AVATAR_SET_TOO_BIG = 0x0004;
const AVATAR_SET_TOO_SMALL = 0x0005;
const AVATAR_SET_BANNED = 0x0006;
const AVATAR_SET_INVALID_TYPE = 0x0007;
const AVATAR_SET_OTHER_ERROR = 0x0008;
exports.AVATAR_SET_SUCCESS = AVATAR_SET_SUCCESS;
exports.AVATAR_SET_BAD_MD5 = AVATAR_SET_BAD_MD5;
exports.AVATAR_SET_NOT_ALLOWED = AVATAR_SET_NOT_ALLOWED;
exports.AVATAR_SET_TEMP_UNAVAILABLE = AVATAR_SET_TEMP_UNAVAILABLE;
exports.AVATAR_SET_TOO_BIG = AVATAR_SET_TOO_BIG;
exports.AVATAR_SET_TOO_SMALL = AVATAR_SET_TOO_SMALL;
exports.AVATAR_SET_BANNED = AVATAR_SET_BANNED;
exports.AVATAR_SET_INVALID_TYPE = AVATAR_SET_INVALID_TYPE;
exports.AVATAR_SET_OTHER_ERROR = AVATAR_SET_OTHER_ERROR;

// BEX 0x0007, File transfer (OBIMP_BEX_FT)
const OBIMP_BEX_FT_CLI_PARAMS = 0x0001;
const OBIMP_BEX_FT_SRV_PARAMS_REPLY = 0x0002;
const OBIMP_BEX_FT_CLI_SRV_SEND_FILE_REQUEST = 0x0003;
const OBIMP_BEX_FT_CLI_SRV_SEND_FILE_REPLY = 0x0004;
const OBIMP_BEX_FT_CLI_SRV_CONTROL = 0x0005;
const OBIMP_BEX_FT_DIR_PROX_ERROR = 0x0101;
const OBIMP_BEX_FT_DIR_PROX_HELLO = 0x0102;
const OBIMP_BEX_FT_DIR_PROX_FILE = 0x0103;
const OBIMP_BEX_FT_DIR_PROX_FILE_REPLY = 0x0104;
const OBIMP_BEX_FT_DIR_PROX_FILE_DATA = 0x0105;
exports.OBIMP_BEX_FT_CLI_PARAMS = OBIMP_BEX_FT_CLI_PARAMS;
exports.OBIMP_BEX_FT_SRV_PARAMS_REPLY = OBIMP_BEX_FT_SRV_PARAMS_REPLY;
exports.OBIMP_BEX_FT_CLI_SRV_SEND_FILE_REQUEST = OBIMP_BEX_FT_CLI_SRV_SEND_FILE_REQUEST;
exports.OBIMP_BEX_FT_CLI_SRV_SEND_FILE_REPLY = OBIMP_BEX_FT_CLI_SRV_SEND_FILE_REPLY;
exports.OBIMP_BEX_FT_CLI_SRV_CONTROL = OBIMP_BEX_FT_CLI_SRV_CONTROL;
exports.OBIMP_BEX_FT_DIR_PROX_ERROR = OBIMP_BEX_FT_DIR_PROX_ERROR;
exports.OBIMP_BEX_FT_DIR_PROX_HELLO = OBIMP_BEX_FT_DIR_PROX_HELLO;
exports.OBIMP_BEX_FT_DIR_PROX_FILE = OBIMP_BEX_FT_DIR_PROX_FILE;
exports.OBIMP_BEX_FT_DIR_PROX_FILE_REPLY = OBIMP_BEX_FT_DIR_PROX_FILE_REPLY;
exports.OBIMP_BEX_FT_DIR_PROX_FILE_DATA = OBIMP_BEX_FT_DIR_PROX_FILE_DATA;

// File transfer reply codes:
const FT_REPLY_CODE_ACCEPT = 0x0001;
const FT_REPLY_CODE_DECLINE = 0x0002;
const FT_REPLY_CODE_DISABLED = 0x0003;
const FT_REPLY_CODE_NOT_ALLOWED	 = 0x0004;
exports.FT_REPLY_CODE_ACCEPT = FT_REPLY_CODE_ACCEPT;
exports.FT_REPLY_CODE_DECLINE = FT_REPLY_CODE_DECLINE;
exports.FT_REPLY_CODE_DISABLED = FT_REPLY_CODE_DISABLED;
exports.FT_REPLY_CODE_NOT_ALLOWED	 = FT_REPLY_CODE_NOT_ALLOWED	;

// File transfer control codes:
const FT_CONTROL_CODE_CANCEL = 0x0001;
const FT_CONTROL_CODE_DIRECT_FAILED = 0x0002;
const FT_CONTROL_CODE_DIRECT_FAILED_TRY_REVERSE = 0x0003;
const FT_CONTROL_CODE_DIRECT_FAILED_TRY_PROXY = 0x0004;
const FT_CONTROL_CODE_PROXY_FAILED = 0x0005;
const FT_CONTROL_CODE_READY = 0x0006;
exports.FT_CONTROL_CODE_CANCEL = FT_CONTROL_CODE_CANCEL;
exports.FT_CONTROL_CODE_DIRECT_FAILED = FT_CONTROL_CODE_DIRECT_FAILED;
exports.FT_CONTROL_CODE_DIRECT_FAILED_TRY_REVERSE = FT_CONTROL_CODE_DIRECT_FAILED_TRY_REVERSE;
exports.FT_CONTROL_CODE_DIRECT_FAILED_TRY_PROXY = FT_CONTROL_CODE_DIRECT_FAILED_TRY_PROXY;
exports.FT_CONTROL_CODE_PROXY_FAILED = FT_CONTROL_CODE_PROXY_FAILED;
exports.FT_CONTROL_CODE_READY = FT_CONTROL_CODE_READY;

const OBIMP_MAX_FILE_DATA_WTDL_LEN = 0x00000800;
exports.OBIMP_MAX_FILE_DATA_WTDL_LEN = OBIMP_MAX_FILE_DATA_WTDL_LEN;

// File transfer error codes:
const FT_ERROR_CODE_TIMEOUT = 0x0001;
const FT_ERROR_CODE_WRONG_UNIQ_FT_ID = 0x0002;
const FT_ERROR_CODE_WRONG_FILE_NAME = 0x0003;
const FT_ERROR_CODE_WRONG_RELATIVE_PATH = 0x0004;
const FT_ERROR_CODE_WRONG_RESUME_POS = 0x0005;
const FT_ERROR_CODE_PROXY_TRAFFIC_LIMIT = 0x0006;
exports.FT_ERROR_CODE_TIMEOUT = FT_ERROR_CODE_TIMEOUT;
exports.FT_ERROR_CODE_WRONG_UNIQ_FT_ID = FT_ERROR_CODE_WRONG_UNIQ_FT_ID;
exports.FT_ERROR_CODE_WRONG_FILE_NAME = FT_ERROR_CODE_WRONG_FILE_NAME;
exports.FT_ERROR_CODE_WRONG_RELATIVE_PATH = FT_ERROR_CODE_WRONG_RELATIVE_PATH;
exports.FT_ERROR_CODE_WRONG_RESUME_POS = FT_ERROR_CODE_WRONG_RESUME_POS;
exports.FT_ERROR_CODE_PROXY_TRAFFIC_LIMIT = FT_ERROR_CODE_PROXY_TRAFFIC_LIMIT;

// BEX 0x0008, Transports (OBIMP_BEX_TP)
const OBIMP_BEX_TP_CLI_PARAMS = 0x0001;
const OBIMP_BEX_TP_SRV_PARAMS_REPLY = 0x0002;
const OBIMP_BEX_TP_SRV_ITEM_READY = 0x0003;
const OBIMP_BEX_TP_CLI_SETTINGS = 0x0004;
const OBIMP_BEX_TP_SRV_SETTINGS_REPLY = 0x0005;
const OBIMP_BEX_TP_CLI_MANAGE = 0x0006;
const OBIMP_BEX_TP_SRV_TRANSPORT_INFO = 0x0007;
const OBIMP_BEX_TP_SRV_SHOW_NOTIF = 0x0008;
const OBIMP_BEX_TP_SRV_OWN_AVATAR_HASH = 0x0009;
exports.OBIMP_BEX_TP_CLI_PARAMS = OBIMP_BEX_TP_CLI_PARAMS;
exports.OBIMP_BEX_TP_SRV_PARAMS_REPLY = OBIMP_BEX_TP_SRV_PARAMS_REPLY;
exports.OBIMP_BEX_TP_SRV_ITEM_READY = OBIMP_BEX_TP_SRV_ITEM_READY;
exports.OBIMP_BEX_TP_CLI_SETTINGS = OBIMP_BEX_TP_CLI_SETTINGS;
exports.OBIMP_BEX_TP_SRV_SETTINGS_REPLY = OBIMP_BEX_TP_SRV_SETTINGS_REPLY;
exports.OBIMP_BEX_TP_CLI_MANAGE = OBIMP_BEX_TP_CLI_MANAGE;
exports.OBIMP_BEX_TP_SRV_TRANSPORT_INFO = OBIMP_BEX_TP_SRV_TRANSPORT_INFO;
exports.OBIMP_BEX_TP_SRV_SHOW_NOTIF = OBIMP_BEX_TP_SRV_SHOW_NOTIF;
exports.OBIMP_BEX_TP_SRV_OWN_AVATAR_HASH = OBIMP_BEX_TP_SRV_OWN_AVATAR_HASH;

// Available OBIMP transport status png file indexes:
const OBIMP_TP_STATUS_INDEX_LOGO = 1;
const OBIMP_TP_STATUS_INDEX_ONLINE = 2;
const OBIMP_TP_STATUS_INDEX_OFFLINE = 3;
const OBIMP_TP_STATUS_INDEX_CONNECTING = 4;
const OBIMP_TP_STATUS_INDEX_NOT_IN_LIST = 5;
const OBIMP_TP_STATUS_INDEX_INVISIBLE = 6;
const OBIMP_TP_STATUS_INDEX_INVISIBLE_FOR_ALL = 7;
const OBIMP_TP_STATUS_INDEX_AWAY = 8;
const OBIMP_TP_STATUS_INDEX_NOT_AVAILABLE = 9;
const OBIMP_TP_STATUS_INDEX_OCCUPIED = 10;
const OBIMP_TP_STATUS_INDEX_DO_NOT_DISTURB = 11;
const OBIMP_TP_STATUS_INDEX_LUNCH = 12;
const OBIMP_TP_STATUS_INDEX_AT_HOME = 13;
const OBIMP_TP_STATUS_INDEX_AT_WORK = 14;
const OBIMP_TP_STATUS_INDEX_FREE_FOR_CHAT = 15;
exports.OBIMP_TP_STATUS_INDEX_LOGO = OBIMP_TP_STATUS_INDEX_LOGO;
exports.OBIMP_TP_STATUS_INDEX_ONLINE = OBIMP_TP_STATUS_INDEX_ONLINE;
exports.OBIMP_TP_STATUS_INDEX_OFFLINE = OBIMP_TP_STATUS_INDEX_OFFLINE;
exports.OBIMP_TP_STATUS_INDEX_CONNECTING = OBIMP_TP_STATUS_INDEX_CONNECTING;
exports.OBIMP_TP_STATUS_INDEX_NOT_IN_LIST = OBIMP_TP_STATUS_INDEX_NOT_IN_LIST;
exports.OBIMP_TP_STATUS_INDEX_INVISIBLE = OBIMP_TP_STATUS_INDEX_INVISIBLE;
exports.OBIMP_TP_STATUS_INDEX_INVISIBLE_FOR_ALL = OBIMP_TP_STATUS_INDEX_INVISIBLE_FOR_ALL;
exports.OBIMP_TP_STATUS_INDEX_AWAY = OBIMP_TP_STATUS_INDEX_AWAY;
exports.OBIMP_TP_STATUS_INDEX_NOT_AVAILABLE = OBIMP_TP_STATUS_INDEX_NOT_AVAILABLE;
exports.OBIMP_TP_STATUS_INDEX_OCCUPIED = OBIMP_TP_STATUS_INDEX_OCCUPIED;
exports.OBIMP_TP_STATUS_INDEX_DO_NOT_DISTURB = OBIMP_TP_STATUS_INDEX_DO_NOT_DISTURB;
exports.OBIMP_TP_STATUS_INDEX_LUNCH = OBIMP_TP_STATUS_INDEX_LUNCH;
exports.OBIMP_TP_STATUS_INDEX_AT_HOME = OBIMP_TP_STATUS_INDEX_AT_HOME;
exports.OBIMP_TP_STATUS_INDEX_AT_WORK = OBIMP_TP_STATUS_INDEX_AT_WORK;
exports.OBIMP_TP_STATUS_INDEX_FREE_FOR_CHAT = OBIMP_TP_STATUS_INDEX_FREE_FOR_CHAT;

// Available settings flags:
const TP_SF_HIDE_SRV_PARAMS = 0x0001;
exports.TP_SF_HIDE_SRV_PARAMS = TP_SF_HIDE_SRV_PARAMS;

// Available options types:
const TP_OT_BOOL = 1;
const TP_OT_BYTE = 2;
const TP_OT_WORD = 3;
const TP_OT_LONGWORD = 4;
const TP_OT_QUADWORD = 5;
const TP_OT_UTF8 = 6;
exports.TP_OT_BOOL = TP_OT_BOOL;
exports.TP_OT_BYTE = TP_OT_BYTE;
exports.TP_OT_WORD = TP_OT_WORD;
exports.TP_OT_LONGWORD = TP_OT_LONGWORD;
exports.TP_OT_QUADWORD = TP_OT_QUADWORD;
exports.TP_OT_UTF8 = TP_OT_UTF8;

// Available options flags:
const TP_OF_CHECK = 0x00000001;
const TP_OF_EDIT = 0x00000002;
const TP_OF_COMBO = 0x00000004;
const TP_OF_LINK = 0x00000008;
const TP_OF_CHANGE = 0x00010000; // (replaces saved value of option)
const TP_OF_READ_ONLY = 0x00020000;
const TP_OF_DISABLED = 0x00040000;

exports.TP_OF_CHECK = TP_OF_CHECK;
exports.TP_OF_EDIT = TP_OF_EDIT;
exports.TP_OF_COMBO = TP_OF_COMBO;
exports.TP_OF_LINK = TP_OF_LINK;
exports.TP_OF_CHANGE = TP_OF_CHANGE;
exports.TP_OF_READ_ONLY = TP_OF_READ_ONLY;
exports.TP_OF_DISABLED = TP_OF_DISABLED;

// Transport settings update result codes:
const TP_SET_RES_SUCCESS = 0x0000;
const TP_SET_RES_ERROR_WRONG_ID = 0x0001;
const TP_SET_RES_ERROR_NOT_FOUND = 0x0002;
const TP_SET_RES_ERROR_NOT_ALLOWED = 0x0003;
exports.TP_SET_RES_SUCCESS = TP_SET_RES_SUCCESS;
exports.TP_SET_RES_ERROR_WRONG_ID = TP_SET_RES_ERROR_WRONG_ID;
exports.TP_SET_RES_ERROR_NOT_FOUND = TP_SET_RES_ERROR_NOT_FOUND;
exports.TP_SET_RES_ERROR_NOT_ALLOWED = TP_SET_RES_ERROR_NOT_ALLOWED;

// Connection managing codes:
const TP_CON_MAN_CONNECT = 0x0001;
const TP_CON_MAN_STATUS = 0x0002;
const TP_CON_MAN_DISCONNECT = 0x0003;
exports.TP_CON_MAN_CONNECT = TP_CON_MAN_CONNECT;
exports.TP_CON_MAN_STATUS = TP_CON_MAN_STATUS;
exports.TP_CON_MAN_DISCONNECT = TP_CON_MAN_DISCONNECT;


// Transport state codes:
const TP_STATE_LOGGEDIN = 0x0000;
const TP_STATE_LOGGEDOFF = 0x0001;
const TP_STATE_STATUS_CHANGED = 0x0002;
const TP_STATE_CON_FAILED = 0x0003;
const TP_STATE_ACCOUNT_INVALID = 0x0004;
const TP_STATE_SERVICE_TEMP_UNAVAILABLE = 0x0005;
const TP_STATE_WRONG_PASSWORD = 0x0006;
const TP_STATE_INVALID_LOGIN = 0x0007;
const TP_STATE_OTHER_PLACE_LOGIN = 0x0008;
const TP_STATE_CANT_LOGIN_TRY_LATER = 0x0009;
const TP_STATE_SRV_PAUSED = 0x000A;
const TP_STATE_SRV_RESUMED = 0x000B;
const TP_STATE_SRV_MIGRATED = 0x000C;

exports.TP_STATE_LOGGEDIN = TP_STATE_LOGGEDIN;
exports.TP_STATE_LOGGEDOFF = TP_STATE_LOGGEDOFF;
exports.TP_STATE_STATUS_CHANGED = TP_STATE_STATUS_CHANGED;
exports.TP_STATE_CON_FAILED = TP_STATE_CON_FAILED;
exports.TP_STATE_ACCOUNT_INVALID = TP_STATE_ACCOUNT_INVALID;
exports.TP_STATE_SERVICE_TEMP_UNAVAILABLE = TP_STATE_SERVICE_TEMP_UNAVAILABLE;
exports.TP_STATE_WRONG_PASSWORD = TP_STATE_WRONG_PASSWORD;
exports.TP_STATE_INVALID_LOGIN = TP_STATE_INVALID_LOGIN;
exports.TP_STATE_OTHER_PLACE_LOGIN = TP_STATE_OTHER_PLACE_LOGIN;
exports.TP_STATE_CANT_LOGIN_TRY_LATER = TP_STATE_CANT_LOGIN_TRY_LATER;
exports.TP_STATE_SRV_PAUSED = TP_STATE_SRV_PAUSED;
exports.TP_STATE_SRV_RESUMED = TP_STATE_SRV_RESUMED;
exports.TP_STATE_SRV_MIGRATED = TP_STATE_SRV_MIGRATED;


// Windows server administration
// BEX subtype
const OBIMP_BEX_WADM_CLI_LOGIN = 0x0001;
const OBIMP_BEX_WADM_SRV_LOGIN_REPLY = 0x0002;
const OBIMP_BEX_WADM_CLI_PARAMS = 0x0003;
const OBIMP_BEX_WADM_SRV_PARAMS_REPLY = 0x0004;
const OBIMP_BEX_WADM_CLI_SET = 0x0005;
const OBIMP_BEX_WADM_SRV_SET_REPLY = 0x0006;
const OBIMP_BEX_WADM_CLI_BROADCAST = 0x0007;
const OBIMP_BEX_WADM_SRV_BROADCAST_REPLY = 0x0008;
const OBIMP_BEX_WADM_CLI_USER = 0x0009;
const OBIMP_BEX_WADM_SRV_USER_REPLY =0x000a;
const OBIMP_BEX_WADM_SRV_STATE = 0x000b;
const OBIMP_BEX_WADM_CLI_LIST = 0x000c;
const OBIMP_BEX_WADM_SRV_LIST_REPLY = 0x000d;
const OBIMP_BEX_WADM_CLI_EXT_LIST_REQ = 0x000e;
const OBIMP_BEX_WADM_SRV_EXT_LIST_REPLY = 0x000f;
const OBIMP_BEX_WADM_CLI_EXT_UPD = 0x0010;
const OBIMP_BEX_WADM_SRV_EXT_UPD_REPLY = 0x0011;
exports.OBIMP_BEX_WADM_CLI_LOGIN = OBIMP_BEX_WADM_CLI_LOGIN;
exports.OBIMP_BEX_WADM_SRV_LOGIN_REPLY = OBIMP_BEX_WADM_SRV_LOGIN_REPLY;
exports.OBIMP_BEX_WADM_CLI_PARAMS = OBIMP_BEX_WADM_CLI_PARAMS;
exports.OBIMP_BEX_WADM_SRV_PARAMS_REPLY = OBIMP_BEX_WADM_SRV_PARAMS_REPLY;
exports.OBIMP_BEX_WADM_CLI_SET = OBIMP_BEX_WADM_CLI_SET;
exports.OBIMP_BEX_WADM_SRV_SET_REPLY = OBIMP_BEX_WADM_SRV_SET_REPLY;
exports.OBIMP_BEX_WADM_CLI_BROADCAST = OBIMP_BEX_WADM_CLI_BROADCAST;
exports.OBIMP_BEX_WADM_SRV_BROADCAST_REPLY = OBIMP_BEX_WADM_SRV_BROADCAST_REPLY;
exports.OBIMP_BEX_WADM_CLI_USER = OBIMP_BEX_WADM_CLI_USER;
exports.OBIMP_BEX_WADM_SRV_USER_REPLY = OBIMP_BEX_WADM_SRV_USER_REPLY;
exports.OBIMP_BEX_WADM_SRV_STATE = OBIMP_BEX_WADM_SRV_STATE;
exports.OBIMP_BEX_WADM_CLI_LIST = OBIMP_BEX_WADM_CLI_LIST;
exports.OBIMP_BEX_WADM_SRV_LIST_REPLY = OBIMP_BEX_WADM_SRV_LIST_REPLY;
exports.OBIMP_BEX_WADM_CLI_EXT_LIST_REQ = OBIMP_BEX_WADM_CLI_EXT_LIST_REQ;
exports.OBIMP_BEX_WADM_SRV_EXT_LIST_REPLY = OBIMP_BEX_WADM_SRV_EXT_LIST_REPLY;
exports.OBIMP_BEX_WADM_CLI_EXT_UPD = OBIMP_BEX_WADM_CLI_EXT_UPD;
exports.OBIMP_BEX_WADM_SRV_EXT_UPD_REPLY = OBIMP_BEX_WADM_SRV_EXT_UPD_REPLY;

// Login result codes:
const ADM_RES_CODE_SUCCESS = 0x0000;
const ADM_RES_CODE_BAD_KEY = 0x0001;
exports.ADM_RES_CODE_SUCCESS = ADM_RES_CODE_SUCCESS;
exports.ADM_RES_CODE_BAD_KEY = ADM_RES_CODE_BAD_KEY;

// Broadcast flags:
const BROADCAST_MSG_TO_ALL = 0x0001;
const BROADCAST_MSG_TO_CONNECTED_ONLY = 0x0002;
const BROADCAST_DROP_CONNECTIONS = 0x0003;
exports.BROADCAST_MSG_TO_ALL = BROADCAST_MSG_TO_ALL;
exports.BROADCAST_MSG_TO_CONNECTED_ONLY = BROADCAST_MSG_TO_CONNECTED_ONLY;
exports.BROADCAST_DROP_CONNECTIONS = BROADCAST_DROP_CONNECTIONS;

// Broadcast result codes:
const BC_RES_SUCCESS = 0x0000;
const BC_RES_BAD_REQUEST = 0x0001;
const BC_RES_MSG_LEN_LIMIT = 0x0002;
exports.BC_RES_SUCCESS = BC_RES_SUCCESS;
exports.BC_RES_BAD_REQUEST = BC_RES_BAD_REQUEST;
exports.BC_RES_MSG_LEN_LIMIT = BC_RES_MSG_LEN_LIMIT;

// Setting change result codes:
const SET_CHANGE_SUCCESS = 0x0000;
const SET_CHANGE_NOT_ALLOWED = 0x0001;
exports.SET_CHANGE_SUCCESS = SET_CHANGE_SUCCESS;
exports.SET_CHANGE_NOT_ALLOWED = SET_CHANGE_NOT_ALLOWED;

// Available extension types:
const EXT_TYPE_TRANSPORT = 0x0001;
exports.EXT_TYPE_TRANSPORT = EXT_TYPE_TRANSPORT;

// Available extensions proxy types:
const EXT_PROXY_TYPE_NONE = 0x00;
const EXT_PROXY_TYPE_HTTP = 0x01;
const EXT_PROXY_TYPE_SOCKS4 = 0x02;
const EXT_PROXY_TYPE_SOCKS4A = 0x03;
const EXT_PROXY_TYPE_SOCKS5 = 0x04;
exports.EXT_PROXY_TYPE_NONE = EXT_PROXY_TYPE_NONE;
exports.EXT_PROXY_TYPE_HTTP = EXT_PROXY_TYPE_HTTP;
exports.EXT_PROXY_TYPE_SOCKS4 = EXT_PROXY_TYPE_SOCKS4;
exports.EXT_PROXY_TYPE_SOCKS4A = EXT_PROXY_TYPE_SOCKS4A;
exports.EXT_PROXY_TYPE_SOCKS5 = EXT_PROXY_TYPE_SOCKS5;

// Extension update settings result codes:
const ADM_EXT_UPD_SET_SUCCESS = 0x0000;
const ADM_EXT_UPD_SET_FAILED = 0x0001;
exports.ADM_EXT_UPD_SET_SUCCESS = ADM_EXT_UPD_SET_SUCCESS;
exports.ADM_EXT_UPD_SET_FAILED = ADM_EXT_UPD_SET_FAILED;

// Available user commands:
const CMD_USER_ADD = 0x0001;
const CMD_USER_DEL = 0x0002;
const CMD_USER_UPD = 0x0003;
const CMD_USER_BAN = 0x0004;
const CMD_USER_UNBAN = 0x0005;
const CMD_USER_KICK = 0x0006;
const CMD_USER_DETAILS = 0x0007;
const CMD_USER_CLEARCL = 0x0008;
exports.CMD_USER_ADD = CMD_USER_ADD;
exports.CMD_USER_DEL = CMD_USER_DEL;
exports.CMD_USER_UPD = CMD_USER_UPD;
exports.CMD_USER_BAN = CMD_USER_BAN;
exports.CMD_USER_UNBAN = CMD_USER_UNBAN;
exports.CMD_USER_KICK = CMD_USER_KICK;
exports.CMD_USER_DETAILS = CMD_USER_DETAILS;
exports.CMD_USER_CLEARCL = CMD_USER_CLEARCL;


// User operation result codes:
const USER_RES_SUCCESS = 0x0000;
const USER_RES_BAD_REQUEST = 0x0001;
const USER_RES_NOT_FOUND = 0x0002;
const USER_RES_ALREADY_EXISTS = 0x0003;
const USER_RES_LEN_LIMIT = 0x0004;
const USER_RES_SERVICE_TEMP_UNAVAILABLE = 0x0005;
exports.USER_RES_SUCCESS = USER_RES_SUCCESS;
exports.USER_RES_BAD_REQUEST = USER_RES_BAD_REQUEST;
exports.USER_RES_NOT_FOUND = USER_RES_NOT_FOUND;
exports.USER_RES_ALREADY_EXISTS = USER_RES_ALREADY_EXISTS;
exports.USER_RES_LEN_LIMIT = USER_RES_LEN_LIMIT;
exports.USER_RES_SERVICE_TEMP_UNAVAILABLE = USER_RES_SERVICE_TEMP_UNAVAILABLE;

// Admin list types:
const LIST_TYPE_CONNECTED = 0x0001;
const LIST_TYPE_REGISTERED = 0x0002;
const LIST_TYPE_LAST_REGED = 0x0003;
exports.LIST_TYPE_CONNECTED = LIST_TYPE_CONNECTED;
exports.LIST_TYPE_REGISTERED = LIST_TYPE_REGISTERED;
exports.LIST_TYPE_LAST_REGED = LIST_TYPE_LAST_REGED;

/*
// Text code
const OBIMP_BEX = {
    1:{
        name:"Common",
        1:"CLI_HELLO",
        2:"SRV_HELLO",
        3:"CLI_LOGIN",
        4:"SRV_LOGIN_REPLY",
        5:"SRV_BYE",
        6:"CLI_SRV_KEEPALIVE_PING",
        7:"CLI_SRV_KEEPALIVE_PONG",
        8:"CLI_REGISTER",
        9:"SRV_REGISTER_REPLY"
    },
    2:{
        name:"Contact list",
        1:"CLI_PARAMS",
        2:"SRV_PARAMS_REPLY",
        3:"CLI_REQUEST",
        4:"SRV_REPLY",
        5:"CLI_VERIFY",
        6:"SRV_VERIFY_REPLY",
        7:"CLI_ADD_ITEM",
        8:"SRV_ADD_ITEM_REPLY",
        9:"CLI_DEL_ITEM",
        10:"SRV_DEL_ITEM_REPLY",
        11:"CLI_UPD_ITEM",
        12:"SRV_UPD_ITEM_REPLY",
        13:"CLI_SRV_AUTH_REQUEST",
        14:"CLI_SRV_AUTH_REPLY",
        15:"CLI_SRV_AUTH_REVOKE",
        16:"CLI_REQ_OFFAUTH",
        17:"SRV_DONE_OFFAUTH",
        18:"CLI_DEL_OFFAUTH",
        19:"SRV_ITEM_OPER",
        20:"SRV_BEGIN_UPDATE",
        21:"SRV_END_UPDATE"
    },
    3:{
        name:"Presence",
        1:"CLI_PARAMS",
        2:"SRV_PARAMS_REPLY",
        3:"CLI_SET_PRES_INFO",
        4:"CLI_SET_STATUS",
        5:"CLI_ACTIVATE",
        6:"SRV_CONTACT_ONLINE",
        7:"SRV_CONTACT_OFFLINE",
        8:"CLI_REQ_PRES_INFO",
        9:"SRV_PRES_INFO",
        10:"SRV_MAIL_NOTIF",
        11:"CLI_REQ_OWN_MAIL_URL",
        12:"SRV_OWN_MAIL_URL"
    },
    4:{
        name:"Instant messaging",
        1:"CLI_PARAMS",
        2:"SRV_PARAMS_REPLY",
        3:"CLI_REQ_OFFLINE",
        4:"SRV_DONE_OFFLINE",
        5:"CLI_DEL_OFFLINE",
        6:"CLI_MESSAGE",
        7:"SRV_MESSAGE",
        8:"CLI_SRV_MSG_REPORT",
        9:"CLI_SRV_NOTIFY",
        10:"CLI_SRV_ENCRYPT_KEY_REQ",
        11:"CLI_SRV_ENCRYPT_KEY_REPLY",
        12:"CLI_MULTIPLE_MSG"
    },
    5:{
        name:"Users directory",
        0x0001:"CLI_PARAMS",
        0x0002:"SRV_PARAMS_REPLY",
        0x0003:"CLI_DETAILS_REQ",
        0x0004:"SRV_DETAILS_REQ_REPLY",
        0x0005:"CLI_DETAILS_UPD",
        0x0006:"SRV_DETAILS_UPD_REPLY",
        0x0007:"CLI_SEARCH",
        0x0008:"SRV_SEARCH_REPLY",
        0x0009:"CLI_SECURE_UPD",
        0x000A:"SRV_SECURE_UPD_REPLY"
    },
    6:{
        name:"User avatars",
        0x0001:"CLI_PARAMS",
        0x0002:"SRV_PARAMS_REPLY",
        0x0003:"CLI_AVATAR_REQ",
        0x0004:"SRV_AVATAR_REPLY",
        0x0005:"CLI_AVATAR_SET",
        0x0006:"SRV_AVATAR_SET_REPLY"
    },
    7:{
        name:"File transfer",
        0x0001:"CLI_PARAMS",
        0x0002:"SRV_PARAMS_REPLY",
        0x0003:"CLI_SRV_SEND_FILE_REQUEST",
        0x0004:"CLI_SRV_SEND_FILE_REPLY",
        0x0005:"CLI_SRV_CONTROL",
        0x0101:"DIR_PROX_ERROR",
        0x0102:"DIR_PROX_HELLO",
        0x0103:"DIR_PROX_FILE",
        0x0104:"DIR_PROX_FILE_REPLY",
        0x0105:"DIR_PROX_FILE_DATA"
    },
    8:{
        name:"Transports",
        0x0001:"CLI_PARAMS",
        0x0002:"SRV_PARAMS_REPLY",
        0x0003:"SRV_ITEM_READY",
        0x0004:"CLI_SETTINGS",
        0x0005:"SRV_SETTINGS_REPLY",
        0x0006:"CLI_MANAGE",
        0x0007:"SRV_TRANSPORT_INFO",
        0x0008:"SRV_SHOW_NOTIF",
        0x0009:"SRV_OWN_AVATAR_HASH"
    },
    9:{
        name:"Admin Command",
        1:"CLI_PARAMS",
        2:"SRV_PARAMS_REPLY"
    }};
const HELLO_ERROR = {
    1:"ACCOUNT_INVALID",
    2:"SERVICE_TEMP_UNAVAILABLE",
    3:"ACCOUNT_BANNED",
    4:"WRONG_COOKIE",
    5:"TOO_MANY_CLIENTS",
    6:"INVALID_LOGIN"
};
const LOGIN_ERROR = {
    1:"ACCOUNT_INVALID",
    2:"SERVICE_TEMP_UNAVAILABLE",
    3:"ACCOUNT_BANNED",
    4:"WRONG_PASSWORD",
    5:"INVALID_LOGIN"
};
const BYE_REASON_TEXT = [
    0,
    'SRV_SHUTDOWN',
    'CLI_NEW_LOGIN',
    'ACCOUNT_KICKED',
    'INCORRECT_SEQ', 'INCORRECT_BEX_TYPE',
    'INCORRECT_BEX_SUB', 'INCORRECT_BEX_STEP',
    'TIMEOUT', 'INCORRECT_WTLD',
    'NOT_ALLOWED', 'FLOODING'
];

*/
